export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  lightGray: '#B3B4B6',
  accent: '#FFC231',
  accentRed: '#FB5D2E',
  accentPink: '#F96165',
};

export const Categories = [
  {
    name: 'Burger',
    image: require('../database/images/burger.png'),
    items: [
      {
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 199,
        isTopOftheWeek: true,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8',
        crust: 'Thick crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        name: 'Aloo Tikki Burger',
        weight: 10,
        rating: '4.5',
        price: 99,
        isTopOftheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 8',
        crust: 'Thick crust',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
        ],
      },
      {
        name: 'Biggie Burger',
        weight: 250,
        rating: '4.2',
        price: 299,
        isTopOftheWeek: false,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10',
        crust: 'Thick crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),

          require('../database/images/Sliced-Onion.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('../database/images/pizza.png'),
    items: [
      {
        name: 'Pepperoni Pizza',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOftheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 16',
        crust: 'thin crust',
        delivery: 30,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        name: 'mexican greenwave Pizza',
        weight: 300,
        rating: '5.0',
        price: 299,
        isTopOftheWeek: true,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 16',
        crust: 'thin cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
        ],
      },
      {
        name: 'Plain Cheese Pizza',
        weight: 230,
        rating: '4.0',
        price: 244,
        isTopOftheWeek: true,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 14',
        crust: 'thin cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/flour.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/cheese.png'),
        ],
      },
    ],
  },
  {
    name: 'soft drinks',
    image: require('../database/images/softdrinks.png'),
    items: [
      {
        name: 'coca cola',
        weight: 500,
        rating: '5.0',
        price: 9,
        isTopOftheWeek: true,
        image: require('../database/images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Samll ICe',
        delivery: 10,
        ingredients: [
          require('../database/images/softdrinks/cocacola.png'),
        ],
      },
      {
        name: 'mango',
        weight: 200,
        rating: '4.0',
        price: 9,
        isTopOftheWeek: false,
        image: require('../database/images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Large ICe',
        delivery: 10,
        ingredients: [
          require('../database/images/softdrinks/mango.png'),
        ],
      },
      {
        name: 'orange',
        weight: 300,
        rating: '4.3',
        price: 7,
        isTopOftheWeek: true,
        image: require('../database/images/softdrinks/orange.png'),
        size: 'Medium Glass',
        crust: 'Samll ICe',
        delivery: 10,
        ingredients: [
          require('../database/images/softdrinks/orange.png'),
        ],
      },
    ],
  },
];
